### ISSUE TITLE
挂了～

### ISSUE THREAD

**Issue by wizardbyron** [timqian/openprompt.co#11]
<img width="1327" alt="截屏2023-03-26 16 15 05" src="https://user-images.githubusercontent.com/1400427/227763670-56117019-9d06-4072-b695-8305037214c6.png">

**Comment by timqian** [comment]
看到截图里 Starred prompts 周围有不应该出现的 scroll bar, 刚加了 `overflow-hidden`, 希望现在没有了

另外我在考虑做完搜索功能之后把这部分去掉，大多用户其实没有 star prompts 的习惯，star 多了这边其实也不好找
