### ISSUE TITLE
又挂了

### ISSUE THREAD

**Issue by wizardbyron** [timqian/openprompt.co#12]
<img width="1307" alt="截屏2023-03-26 20 29 02" src="https://user-images.githubusercontent.com/1400427/227775711-6a4611e1-0c9f-4c7f-9215-5282a7c481ec.png">

**Comment by timqian** [comment]
应该是和网络有关，我这边没有复现

**Comment by wizardbyron** [comment]
<img width="927" alt="截屏2023-03-26 20 45 16" src="https://user-images.githubusercontent.com/1400427/227776584-284bbb4c-7efc-474f-bf43-e056edd17b7f.png">

**Comment by timqian** [comment]
How can I reproduce it?

**Comment by wizardbyron** [comment]
<img width="1780" alt="截屏2023-03-26 21 48 47" src="https://user-images.githubusercontent.com/1400427/227780220-dcf6365a-112b-4656-b716-406ff769a899.png">

**Comment by wizardbyron** [comment]
<img width="1122" alt="截屏2023-03-26 21 50 11" src="https://user-images.githubusercontent.com/1400427/227780294-4c6b1c7c-91f2-4113-9be1-e36e7c631d95.png">

**Comment by wizardbyron** [comment]
Github Sign In 的时候

**Comment by timqian** [comment]
好像找到原因了，我在你的账号下 https://openprompt.co/wizardbyron 找到了一个 handle 为空的 prompt (随便聊聊)。
<img width="454" alt="Screen Shot 2023-03-26 at 22 54 51" src="https://user-images.githubusercontent.com/5512552/227784173-f66f49ae-36a4-4c75-a150-cae2d7188813.png">
应该是这个导致的。我看它没有内容，把它删了，你看现在可以了嘛？

**Comment by timqian** [comment]
我来给各处加个限制，让它不能为空

**Comment by wizardbyron** [comment]
OK啦
