### ISSUE TITLE
我删除了一个自己的  Prompt，又挂了

### ISSUE THREAD

**Issue by wizardbyron** [timqian/openprompt.co#14]
<img width="858" alt="截屏2023-03-27 17 17 45" src="https://user-images.githubusercontent.com/1400427/227898464-7e886cc3-922f-4e81-a84c-026c1a6e2195.png">

**Comment by timqian** [comment]
OMG, 这次是整个站挂了，我看一下

**Comment by timqian** [comment]
注意到这个问题又出现了一次，已修复了，原因是数据库设定了不允许删除别人的 star。之前测试没覆盖到这个逻辑
