### ISSUE TITLE
打不开了

### ISSUE THREAD

**Issue by wizardbyron** [timqian/openprompt.co#31]
<img width="693" alt="截屏2023-04-02 21 18 20" src="https://user-images.githubusercontent.com/1400427/229355314-99853130-8050-435e-b422-7b0f1df1411c.png">

**Comment by wizardbyron** [comment]
可以ping通，看看证书是不是过期了？

**Comment by tianheg** [comment]
网站被墙了，要用代理

**Comment by wizardbyron** [comment]
> 网站被墙了，要用代理

我用代理也不行

**Comment by tianheg** [comment]
如果用的机场代理，可以试试更换其它地方节点；

如果不是，可以在浏览器隐私模式下试试能否访问

**Comment by timqian** [comment]
@wizardbyron 可能是你的代理是白名单模式，而 openprompt 没有在名单里。可以试试全局模式

**Comment by wizardbyron** [comment]
<img width="669" alt="截屏2023-04-03 10 14 39" src="https://user-images.githubusercontent.com/1400427/229396417-82902dbe-0f06-4841-8e28-b8246a3eecc3.png">
Too Many Redirections

**Comment by timqian** [comment]
@wizardbyron 全局 vpn 也是如此吗？之前有些用户反馈用了 vpn 也访问不了，但是切换成全局 vpn 就可以了

网站本身应该是没挂的 https://www.freshworks.com/website-monitoring/is-it-down/openprompt.co

**Comment by Jing-Xin** [comment]
![image](https://user-images.githubusercontent.com/13760082/229426390-fb9a0be4-1b4a-4ea9-b372-01ede7604f00.png)

**Comment by timqian** [comment]
@Jing-Xin 被墙了，并且很多用户的 vpn 是白名单模式，openprompt.co 一般不会在那个名单里。如果实在访问不到并且是 pro 用户，可以把 pro 账户的邮箱发给我退款，我的邮箱是 timqian@t9t.io
