### ISSUE TITLE
付费后仍然提示我要升级到 Pro

### ISSUE THREAD

**Issue by wizardbyron** [timqian/openprompt.co#4]
我准备付费，但有个担心：在 lemonsqueezy 看不到和我的帐户关联的消息。

**Comment by wizardbyron** [comment]
担心的事情发生了：付费后仍然提示我要升级到 Pro

**Comment by wizardbyron** [comment]
点击了邮件的链接，现在完全不返回内容了

**Comment by timqian** [comment]
@wizardbyron 抱歉给你打来了困扰，我在OpemPrompt 的数据库没找到你付款时用的邮箱地址，可能是因为邮箱不一样。你可以私发我一下，我手动绑定一下
email: timqian@t9t.io
twitter: twitter.com/tim_qian
