### ISSUE TITLE
每个用户每天用10次就要升级为Pro版

### ISSUE THREAD

**Issue by disanping** [timqian/openprompt.co#5]
请问，怎么升级，作者是有付费计划吗？

**Comment by MatrixAge** [comment]
付费了 账户依然不是pro，邮箱是这个：xiewendao123@foxmail.com 使用github注册的。
@timqian

**Comment by timqian** [comment]
@MatrixAge 我看了下数据库， 你的账号应该已经是 pro 了，可能是之前有延迟，你再试下？

**Comment by MatrixAge** [comment]
> @MatrixAge 我看了下数据库， 你的账号应该已经是 pro 了，可能是之前有延迟，你再试下？

过了大概2分钟才pro了，而且没有通知，没有pro标识...

**Comment by timqian** [comment]
- 升级 pro 流程已优化至 < 5s
- 购买成功之后会跳转到 https://openprompt.co/plan 页面，方便查看当前订阅情况

后续还会增加补充订阅时间的功能。感谢反馈

**Comment by duoluodexiaoxiaoyuan** [comment]
想问下是怎么收费的，网站做的好好

**Comment by timqian** [comment]
@duoluodexiaoxiaoyuan https://openprompt.co/plan 登录之后可以在这里看到付款链接，收费方式目前比较简单，每月 ¥29 不限次数
